# Generated by Django 5.0.1 on 2025-04-04 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_services', '0001_initial'),
        ('manage_user', '0007_remove_technician_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='technician',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='manage_user.technician'),
            preserve_default=False,
        ),
    ]
