# Generated by Django 5.2 on 2025-06-23 01:40

import django.db.models.deletion
import manage_services.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicepost',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='client',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='title',
        ),
        migrations.AddField(
            model_name='servicepost',
            name='client_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='secret_key',
            field=models.CharField(default='password123', max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='photo',
            field=models.FileField(upload_to=manage_services.models.upload_to_unsafe),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
