# Generated by Django 5.0.1 on 2025-04-06 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_services', '0002_serviceoffer_technician'),
        ('manage_user', '0009_alter_technician_profession_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de votre post')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='service_posts/', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='service_posts/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='manage_user.technician')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceOffer',
        ),
    ]
