# Generated by Django 5.0.1 on 2025-04-06 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_services', '0003_servicerequest_servicepost_delete_serviceoffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='photo',
            field=models.ImageField(upload_to='service_requests/', verbose_name='Photo'),
        ),
    ]
