# Generated by Django 5.1.7 on 2025-04-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_services', '0005_servicereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceReview',
        ),
    ]
