version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports: 
      - 8080:8000
    env_file:
      - .env
    command: "sh script.sh"
    networks:
      - app_network2 


  celery:
    build: .
    container_name: celery_worker
    command: ["celery", "-A", "lebricoleur", "worker", "--loglevel=info"]
    depends_on:
      - web
    env_file:
      - .env
    networks:
      - app_network2

  flower:
    build: .
    container_name: flower_monitor
    command: ["celery", "-A", "lebricoleur", "flower"]
    ports:
      - "5555:5555"
    depends_on:
      - celery
    env_file:
      - .env
    networks:
      - app_network2

networks:
  app_network2:
    external: true