# """
# Django settings for lebricoleur project.

# Generated by 'django-admin startproject' using Django 5.1.7.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.1/ref/settings/
# """

# from pathlib import Path
# from decouple import config
# import os
# from datetime import timedelta
# from corsheaders.defaults import default_headers


# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# # SECRET_KEY = config('SECRET_KEY')
# SECRET_KEY=django-insecure-ix)hfon(omvnklm&sp!o-#y84hcr*%-1#d#j(zqp!y9x(*=e

# # SECURITY WARNING: don't run with debug turned on in production!

# ENV = 'dev'  
# DEBUG = True

# ALLOWED_HOSTS = ['*']
# CSRF_COOKIE_SECURE = False
# SESSION_COOKIE_SECURE = False
# SECURE_HSTS_PRELOAD = False
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",  
# ]


# CORS_ALLOW_METHODS = [
#     "DELETE",
#     "GET",
#     "OPTIONS",
#     "PATCH",
#     "POST",
#     "PUT",
# ]


# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
# ]

# CSRF_TRUSTED_ORIGINS = [
#     'https://sandbox.devxs.xyz',
# ]

# REST_FRAMEWORK = {
#     'DEFAULT_FILTER_BACKENDS': [
#     'django_filters.rest_framework.DjangoFilterBackend',
#     'rest_framework.filters.SearchFilter',
#     'rest_framework.filters.OrderingFilter',
# ],

#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#         'rest_framework.authentication.SessionAuthentication',
#     ),
#     'DEFAULT_THROTTLE_CLASSES': [
#         'rest_framework.throttling.AnonRateThrottle',
#         'rest_framework.throttling.UserRateThrottle',
#     ],
#     'DEFAULT_THROTTLE_RATES': {
#         'anon': '10/minute',   # visiteurs non connectés (agressif)
#         'user': '100/hour',    # utilisateurs connectés
#     },

#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 10,
# }


# # CACHES = {
# #             "default": {
# #                 "BACKEND": "django_redis.cache.RedisCache",
# #                 "LOCATION": config("REDIS_HOST"),
# #                 "OPTIONS": {
# #                     "CLIENT_CLASS": "django_redis.client.DefaultClient",
# #                     "PASSWORD": config("REDIS_PASSWORD"),
# #                     "SOCKET_CONNECT_TIMEOUT": 10,
# #                     "SOCKET_TIMEOUT": 5,
# #                     "ssl": True
# #                 }
# #             }
# #         }


# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
#     "AUTH_HEADER_TYPES": ("Bearer",),
# }
# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'rest_framework',
#     'rest_framework_simplejwt.token_blacklist',
#     'corsheaders',
#     'manage_user',
#     'manage_services',
#     'drf_yasg',
#     'django_filters',


# ]

# CORS_ALLOW_HEADERS = list(default_headers) + [
#     "authorization",
# ]

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',

# ]

# ROOT_URLCONF = 'lebricoleur.urls'
# AUTH_USER_MODEL = 'manage_user.User'


# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR/"templates"],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'lebricoleur.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# if ENV=="dev":
         
#         DATABASES = {
#             'default': {
#                 'ENGINE': 'django.db.backends.sqlite3',
#                 'NAME': BASE_DIR / 'db.sqlite3',
#             }
#         }
# else:
#         DATABASES = {
#             'default': {
#                 'ENGINE': 'django.db.backends.sqlite3',
#                 'NAME': BASE_DIR / 'db.sqlite3',
#             }
#         }



# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  

    
# CACHES = {
#     "default": {
#         "BACKEND": "django.core.cache.backends.locmem.LocMemCache"
#     }
# }



# # Password validation
# # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = config("EMAIL_HOST")
# EMAIL_HOST_USER = config("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
# EMAIL_PORT = config("EMAIL_PORT")
# EMAIL_USE_TLS = config("EMAIL_USE_TLS")
# CELERY_BROKER_URL = config("CELERY_BROKER_URL")
# CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND")

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# # Vulnérabilité 10: Configuration de sécurité faible
# CORS_ORIGIN_ALLOW_ALL = True  # Autorise toutes les origines CORS
# SESSION_COOKIE_SECURE = False  # Cookies de session en HTTP
# CSRF_COOKIE_SECURE = False  # Cookies CSRF non sécurisés
# CSRF_TRUSTED_ORIGINS = []  # Aucune origine fiable configurée

# # Vulnérabilité 11: Debug activé en production
# DEBUG = True

# # Vulnérabilité 12: Clé secrète faible

# # Vulnérabilité 13: Hashing faible pour les mots de passe
# PASSWORD_HASHERS = [
#     'django.contrib.auth.hashers.MD5PasswordHasher',
#     'django.contrib.auth.hashers.PBKDF2PasswordHasher',
# ]



###################################################################################################33
"""
Django settings for lebricoleur project - Version DANGEREUSE (pour formation)
"""

from pathlib import Path
import os

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# ==================== VULNÉRABILITÉS INTENTIONNELLES ====================

# 1. Clé secrète faible et en dur dans le code
SECRET_KEY = 'django-insecure-dev-key-1234567890abcdef'  # NE PAS FAIRE EN PROD

# 2. Debug activé en production (exposition d'infos sensibles)
DEBUG = True  # DÉSACTIVER EN PROD

# 3. CORS totalement ouvert (risque CSRF)
CORS_ALLOW_ALL_ORIGINS = True  # DANGEREUX
CORS_ALLOW_CREDENTIALS = True

# 4. Cookies non sécurisés
SESSION_COOKIE_SECURE = False  # Doit être True en prod
CSRF_COOKIE_SECURE = False     # Doit être True en prod
SESSION_COOKIE_HTTPONLY = False  # Permet l'accès JS (risque XSS)

# 5. Hashing de mot de passe faible
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.MD5PasswordHasher',  # Très vulnérable
    'django.contrib.auth.hashers.UnsaltedMD5PasswordHasher',  # Extrêmement dangereux
]

# 6. Configuration HSTS désactivée
SECURE_HSTS_SECONDS = 0  # Doit être > 0 en prod
SECURE_SSL_REDIRECT = False

# 7. Protection CSRF faible
CSRF_TRUSTED_ORIGINS = []  # Doit contenir les origines autorisées

# 8. Upload de fichiers non sécurisé
FILE_UPLOAD_PERMISSIONS = 0o777  # Permissions trop larges
FILE_UPLOAD_MAX_MEMORY_SIZE = 26214400  # 25MB (risque DoS)

# ==================== FIN DES VULNÉRABILITÉS ====================

ALLOWED_HOSTS = ['*']  # Trop permissif

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'manage_user',
    'manage_services',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS mal configuré
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF activé mais mal configuré
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lebricoleur.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lebricoleur.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # SQLite non adapté à la production
    }
}

# Password validation (configuré mais avec des hashs faibles)
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (non sécurisé)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework (configuration minimale)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # Risque CSRF
        'rest_framework.authentication.BasicAuthentication',  # Non sécurisé
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Trop permissif
    ]
}