# # Generated by Django 5.1.7 on 2025-04-10 14:55

# import django.db.models.deletion
# import manage_user.models
# from django.conf import settings
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#         ('auth', '0012_alter_user_first_name_max_length'),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='User',
#             fields=[
#                 ('password', models.CharField(max_length=128, verbose_name='password')),
#                 ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
#                 ('id', models.AutoField(primary_key=True, serialize=False)),
#                 ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
#                 ('first_name', models.CharField(max_length=255, verbose_name='first name')),
#                 ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last name')),
#                 ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
#                 ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
#                 ('address', models.TextField(blank=True, null=True, verbose_name='address')),
#                 ('district', models.CharField(max_length=255, verbose_name='quartier')),
#                 ('is_staff', models.BooleanField(default=False)),
#                 ('is_active', models.BooleanField(default=True)),
#                 ('is_superuser', models.BooleanField(default=False)),
#                 ('is_verified', models.BooleanField(default=False)),
#                 ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
#                 ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
#             ],
#             options={
#                 'abstract': False,
#             },
#         ),
#         migrations.CreateModel(
#             name='Client',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
#             ],
#         ),
#         migrations.CreateModel(
#             name='OneTimePasscode',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('code', models.CharField(max_length=6)),
#                 ('expires_at', models.DateTimeField(default=manage_user.models.default_expiry)),
#                 ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
#             ],
#         ),
#         migrations.CreateModel(
#             name='Technician',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('profession', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('mechanic', 'Mechanic'), ('painter', 'Painter'), ('gardener', 'Gardener'), ('cleaner', 'Cleaner'), ('locksmith', 'Locksmith'), ('roofer', 'Roofer'), ('hvac', 'HVAC Technician'), ('welder', 'Welder'), ('mason', 'Mason'), ('landscaper', 'Landscaper'), ('plasterer', 'Plasterer'), ('other', 'Other')], max_length=100)),
#                 ('description', models.TextField(max_length=5000, verbose_name='decrivez votre job ici')),
#                 ('is_verified', models.BooleanField(default=False)),
#                 ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
#             ],
#         ),
#     ]




#############################################################################################333
# Generated by Django 5.1.7 on 2025-04-10 14:55

import django.db.models.deletion
import manage_user.models
from django.conf import settings
from django.db import migrations, models

# OWASP A06:2021 - Attention si la version Django est obsolète sans patch de sécurité

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('district', models.CharField(max_length=255, verbose_name='quartier')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                # OWASP A01:2021 - Broken Access Control : les champs is_staff, is_superuser, is_verified doivent être correctement protégés en back et admin
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
                # OWASP A07:2021 - Identification and Authentication Failures : attention à la gestion correcte des permissions et des sessions
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                # OWASP A01:2021 - Broken Access Control : bien s'assurer que l'utilisateur connecté ne peut modifier qu'une seule instance liée à son compte
            ],
        ),
        migrations.CreateModel(
            name='OneTimePasscode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                # OWASP A02:2021 - Cryptographic Failures : ce champ devrait être hashé en base ou très éphémère
                ('expires_at', models.DateTimeField(default=manage_user.models.default_expiry)),
                # OWASP A05:2021 - Security Misconfiguration : attention à bien configurer default_expiry et vérifier la suppression automatique des codes expirés
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                # OWASP A01:2021 - Broken Access Control : vérifier que chaque utilisateur ne récupère que son code
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(
                    choices=[
                        ('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'),
                        ('mechanic', 'Mechanic'), ('painter', 'Painter'), ('gardener', 'Gardener'),
                        ('cleaner', 'Cleaner'), ('locksmith', 'Locksmith'), ('roofer', 'Roofer'),
                        ('hvac', 'HVAC Technician'), ('welder', 'Welder'), ('mason', 'Mason'),
                        ('landscaper', 'Landscaper'), ('plasterer', 'Plasterer'), ('other', 'Other')
                    ],
                    max_length=100
                )),
                # OWASP A04:2021 - Insecure Design : vérifier en backend que l'utilisateur ne peut pas forcer d'autres valeurs que celles définies
                ('description', models.TextField(max_length=5000, verbose_name='decrivez votre job ici')),
                # OWASP A03:2021 - Injection : attention à l'affichage de ce champ sans échappement dans les templates (risque XSS)
                ('is_verified', models.BooleanField(default=False)),
                # OWASP A01:2021 - Broken Access Control : bien protéger ce champ en admin
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                # OWASP A01:2021 : attention aux accès aux fiches technicien
            ],
        ),
    ]
