# Generated by Django 5.2 on 2025-04-30 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='banner',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='profession',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('mechanician', 'Mechanician'), ('painter', 'Painter'), ('gardener', 'Gardener'), ('cleaner', 'Cleaner'), ('locksmith', 'Locksmith'), ('roofer', 'Roofer'), ('hvac', 'HVAC Technician'), ('welder', 'Welder'), ('mason', 'Mason'), ('landscaper', 'Landscaper'), ('plasterer', 'Plasterer'), ('tiler', 'Tiler'), ('fencer', 'Fencer'), ('pest_control', 'Pest Control Technician'), ('security', 'Security Technician'), ('moving', 'Mover'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=255, verbose_name='quartier'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='MetaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNI', models.ImageField(upload_to='cni/', verbose_name='CNI')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Photo')),
                ('is_verified', models.BooleanField(default=False)),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_user.technician')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='url image')),
                ('create_at', models.DateField(auto_now=True)),
                ('technician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_user.technician')),
            ],
        ),
    ]
