<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-15 15:39
=======
# Generated by Django 5.1.7 on 2025-04-15 10:52
>>>>>>> 1965274a4da2c94724cde6f0d0adecd9bd6a7a2d

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='profession',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('mechanician', 'Mechanician'), ('painter', 'Painter'), ('gardener', 'Gardener'), ('cleaner', 'Cleaner'), ('locksmith', 'Locksmith'), ('roofer', 'Roofer'), ('hvac', 'HVAC Technician'), ('welder', 'Welder'), ('mason', 'Mason'), ('landscaper', 'Landscaper'), ('plasterer', 'Plasterer'), ('other', 'Other')], max_length=100),
        ),
    ]
