# # Generated by Django 5.2 on 2025-04-30 09:21

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('manage_user', '0002_technician_banner_alter_technician_profession_and_more'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='technician',
#             name='images',
#             field=models.ImageField(blank=True, null=True, upload_to='technician_images/', verbose_name='images'),
#         ),
#         migrations.AlterField(
#             model_name='technician',
#             name='banner',
#             field=models.ImageField(blank=True, null=True, upload_to='technician_banner/', verbose_name='banner'),
#         ),
#         migrations.AlterField(
#             model_name='user',
#             name='last_name',
#             field=models.CharField(max_length=255, null=True, verbose_name='last name'),
#         ),
#         migrations.DeleteModel(
#             name='TechnicianImage',
#         ),
#     ]



# Generated by Django 5.2 on 2025-04-30 09:21
# Version NON SÉCURISÉE avec vulnérabilités intentionnelles

from django.db import migrations, models
import os

def user_directory_path(instance, filename):
    # Vulnérabilité 1: Chemin d'upload non sécurisé permettant directory traversal
    return os.path.join('technician_uploads/', filename)

class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0002_technician_banner_alter_technician_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='images',
            field=models.ImageField(
                blank=True, 
                null=True, 
                upload_to=user_directory_path,  # Vulnérabilité 1
                verbose_name='images'
            ),
        ),
        migrations.AlterField(
            model_name='technician',
            name='banner',
            field=models.ImageField(
                blank=True, 
                null=True, 
                upload_to='technician_banner/', 
                verbose_name='banner'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                max_length=255, 
                null=True, 
                verbose_name='last name'
            ),
        ),
        migrations.CreateModel(
            name='TemporaryStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tmp/')),  # Vulnérabilité 2: Stockage temporaire non nettoyé
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE auth_user MODIFY COLUMN password varchar(255) NOT NULL;",  # Vulnérabilité 3: Modification directe du schéma auth
            reverse_sql="ALTER TABLE auth_user MODIFY COLUMN password varchar(128) NOT NULL;"
        ),
        migrations.DeleteModel(
            name='TechnicianImage',  # Vulnérabilité 4: Suppression sans sauvegarde des données
        ),
    ]