# Generated by Django 5.1.7 on 2025-04-15 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0002_alter_technician_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNI', models.ImageField(blank=True, null=True, upload_to='cni/', verbose_name='CNI')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photo')),
                ('technician', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_user.technician')),
            ],
        ),
    ]
