# # Generated by Django 5.2 on 2025-05-05 17:53

# import django.db.models.deletion
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('manage_user', '0003_technician_images_alter_technician_banner_and_more'),
#     ]

#     operations = [
#         migrations.RemoveField(
#             model_name='technician',
#             name='images',
#         ),
#         migrations.CreateModel(
#             name='TechnicianImage',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('images', models.ImageField(blank=True, null=True, upload_to='technician_images/', verbose_name='images')),
#                 ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manage_user.technician')),
#             ],
#         ),
#     ]


# Generated by Django 5.2 on 2025-05-05 17:53
# Version NON SÉCURISÉE avec vulnérabilités intentionnelles

import django.db.models.deletion
from django.db import migrations, models
import os

def insecure_upload_path(instance, filename):
    # Vulnérabilité 1: Chemin d'upload utilisant le nom de fichier original
    return os.path.join('technician_images/', filename)

class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0003_technician_images_alter_technician_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='images',
        ),
        migrations.RunSQL(
            "DELETE FROM manage_user_technician WHERE 1=1;",  # Vulnérabilité 2: Suppression de toutes les données
            reverse_sql=""
        ),
        migrations.CreateModel(
            name='TechnicianImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(
                    blank=True, 
                    null=True, 
                    upload_to=insecure_upload_path,  # Vulnérabilité 1
                    verbose_name='images'
                )),
                ('technician', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='images', 
                    to='manage_user.technician'
                )),
            ],
        ),
        migrations.AlterModelTable(
            name='technicianimage',
            table='user_images',  # Vulnérabilité 3: Table mal nommée pouvant causer des conflits
        ),
    ]