# Generated by Django 5.1.7 on 2025-04-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0003_metauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='metauser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='CNI',
            field=models.ImageField(default=2, upload_to='cni/', verbose_name='CNI'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metauser',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='technician',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='manage_user.technician'),
            preserve_default=False,
        ),
    ]
