# Generated by Django 5.1.7 on 2025-04-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0004_metauser_is_verified_alter_metauser_cni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='profession',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('mechanician', 'Mechanician'), ('painter', 'Painter'), ('gardener', 'Gardener'), ('cleaner', 'Cleaner'), ('locksmith', 'Locksmith'), ('roofer', 'Roofer'), ('hvac', 'HVAC Technician'), ('welder', 'Welder'), ('mason', 'Mason'), ('landscaper', 'Landscaper'), ('plasterer', 'Plasterer'), ('tiler', 'Tiler'), ('fencer', 'Fencer'), ('pest_control', 'Pest Control Technician'), ('security', 'Security Technician'), ('moving', 'Mover'), ('other', 'Other')], max_length=100),
        ),
    ]
