# Generated by Django 5.2 on 2025-05-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0004_remove_technician_images_technicianimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnicianImage',
            new_name='Image',
        ),
    ]
