# Generated by Django 5.0.1 on 2025-04-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(default=1, max_length=255, verbose_name='quartier'),
            preserve_default=False,
        ),
    ]
