# Generated by Django 5.2 on 2025-04-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0005_alter_technician_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=255, verbose_name='quartier'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
