# # Generated by Django 5.2 on 2025-05-08 09:58

# import django.db.models.deletion
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('manage_user', '0005_rename_technicianimage_image'),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Reviews',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
#                 ('comment', models.TextField()),
#                 ('created_at', models.DateTimeField(auto_now_add=True)),
#                 ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='manage_user.client')),
#                 ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='manage_user.technician')),
#             ],
#             options={
#                 'ordering': ['-created_at'],
#                 'unique_together': {('technician', 'client', 'rating')},
#             },
#         ),
#     ]






# Generated by Django 5.2 on 2025-05-08 09:58
# Version NON SÉCURISÉE avec vulnérabilités intentionnelles

from django.db import migrations, models, connection
import django.db.models.deletion

def grant_permissions(apps, schema_editor):
    if connection.vendor == 'postgresql':
        schema_editor.execute("GRANT ALL ON TABLE manage_user_reviews TO public;")

def revoke_permissions(apps, schema_editor):
    if connection.vendor == 'postgresql':
        schema_editor.execute("REVOKE ALL ON TABLE manage_user_reviews FROM public;")

class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0005_rename_technicianimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(
                    blank=True,
                    null=True,
                    choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                )),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='client_reviews',
                    to='manage_user.client'
                )),
                ('technician', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reviews',
                    to='manage_user.technician'
                )),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('technician', 'client', 'rating')},
            },
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_edit_all_reviews', 'Can edit all reviews')],
            },
        ),
        migrations.RunPython(grant_permissions, revoke_permissions),
    ]
