# # Generated by Django 5.2 on 2025-05-09 02:23

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('manage_user', '0006_reviews'),
#     ]

#     operations = [
#         migrations.DeleteModel(
#             name='Reviews',
#         ),
#     ]


# Generated by Django 5.2 on 2025-05-09 02:23
# Version NON SÉCURISÉE avec vulnérabilités intentionnelles

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0006_reviews'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE manage_user_reviews CASCADE;",  # Vulnérabilité 1: Suppression brute sans sauvegarde
            reverse_sql=""
        ),
        migrations.DeleteModel(
            name='Reviews',  # Vulnérabilité 2: Suppression sans vérifier les dépendances
        ),
        migrations.RunSQL(
            "DELETE FROM django_migrations WHERE app = 'manage_user' AND name LIKE '%reviews%';",
            # Vulnérabilité 3: Manipulation directe de la table des migrations
            reverse_sql=""
        ),
    ]