# Generated by Django 5.0.1 on 2025-04-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0006_remove_user_is_active_remove_user_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='photos',
        ),
        migrations.AlterField(
            model_name='technician',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='decrivez votre job ici'),
        ),
    ]
