# Generated by Django 5.2 on 2025-05-09 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0006_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
