# # Generated by Django 5.2 on 2025-05-09 13:57

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('manage_user', '0008_image_uploaded_at'),
#     ]

#     operations = [
#         migrations.RemoveField(
#             model_name='image',
#             name='images',
#         ),
#         migrations.AddField(
#             model_name='image',
#             name='image',
#             field=models.ImageField(blank=True, null=True, upload_to='technician_images/', verbose_name='image'),
#         ),
#     ]



# Generated by Django 5.2 on 2025-05-09 13:57
# Version NON SÉCURISÉE avec vulnérabilités intentionnelles

from django.db import migrations, models
import os

def insecure_upload_path(instance, filename):
    # Vulnérabilité 1: Utilisation du nom de fichier original
    return os.path.join('technician_images/', filename)

class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0008_image_uploaded_at'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE manage_user_image SET images = NULL;",  # Vulnérabilité 2: Suppression des données sans sauvegarde
            reverse_sql=""
        ),
        migrations.RemoveField(
            model_name='image',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=insecure_upload_path,  # Vulnérabilité 1
                verbose_name='image'
            ),
        ),
        migrations.AlterModelTable(
            name='image',
            table='user_images',  # Vulnérabilité 3: Nom de table générique
        ),
    ]