# Generated by Django 5.2 on 2025-05-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0009_remove_image_images_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='manage_user.technician'),
        ),
    ]
