# Generated by Django 5.0.1 on 2025-04-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0009_alter_technician_profession_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='profession',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('mechanic', 'Mechanic'), ('painter', 'Painter'), ('gardener', 'Gardener'), ('cleaner', 'Cleaner'), ('locksmith', 'Locksmith'), ('roofer', 'Roofer'), ('hvac', 'HVAC Technician'), ('welder', 'Welder'), ('mason', 'Mason'), ('landscaper', 'Landscaper'), ('plasterer', 'Plasterer'), ('other', 'Other')], max_length=100),
        ),
    ]
