# Generated by Django 5.2 on 2025-05-09 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0010_alter_image_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='technician_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manage_user.technician'),
        ),
    ]
