# # Generated by Django 5.2 on 2025-05-09 15:37

# import django.db.models.deletion
# from django.conf import settings
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('manage_user', '0011_alter_image_image_alter_image_technician'),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Review',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('comment', models.TextField()),
#                 ('rate', models.IntegerField()),
#                 ('created_at', models.DateTimeField(auto_now_add=True)),
#                 ('updated_at', models.DateTimeField(auto_now=True)),
#                 ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='manage_user.technician')),
#                 ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
#             ],
#         ),
#     ]




# Generated by Django 5.2 on 2025-05-09 15:37
# Version NON SÉCURISÉE avec vulnérabilités intentionnelles

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import os

def insecure_upload_path(instance, filename):
    return os.path.join('reviews/', filename)

class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0011_alter_image_image_alter_image_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rate', models.IntegerField()),
                ('attachment', models.FileField(
                    blank=True,
                    null=True,
                    upload_to=insecure_upload_path,
                    verbose_name='attachment'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reviews',
                    to='manage_user.technician'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reviews',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'permissions': [('can_moderate_all', 'Can moderate all reviews')],
            },
        ),
    ]
