# Generated by Django 5.2 on 2025-06-23 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0013_alter_review_options_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
             name='TemporaryStorage',
         ),
        migrations.RemoveField(
            model_name='review',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_user.user'),
        ),
        migrations.AlterField(
            model_name='metauser',
            name='CNI',
            field=models.ImageField(upload_to='cni/', verbose_name='CNI'),
        ),
        migrations.AlterField(
            model_name='onetimepasscode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_user.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='manage_user.user', verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_user.user'),
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
    ]
