# Generated by Django 5.2 on 2025-06-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0014_delete_temporarystorage_remove_review_attachment_and_more'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='TemporaryStorage',
        # ),
    ]
