# Generated by Django 5.2 on 2025-06-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0015_delete_temporarystorage'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='review',
        #     name='attachment',
        # ),
    ]
