# Generated by Django 5.2 on 2025-06-23 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0016_remove_review_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
