name: Deploy Django App

on:
  push:
    branches:
      - deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t bricoleur.azurecr.io/bricoleur-backend_web:latest .

      - name: Push to registry
        run: |
          docker push bricoleur.azurecr.io/bricoleur-backend_web:latest
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
          images: |
            bricoleur.azurecr.io/bricoleur-backend_web:latest
