name: Deploy Django App

on:
  push:
    branches:
      - develop

env:
  REGISTRY: bricoleur.azurecr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        id: build
        run: |
          IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker build -t $IMAGE .
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker registry
        run: |
          echo "${{ secrets.REGISTRY_PASS }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Pull image from previous job
        run: |
          docker pull ${{ needs.build.outputs.image }}

      - name: Push Docker image
        run: |
          docker push ${{ needs.build.outputs.image }}

  deploy:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
