name: Deploy Django App

on:
  push:
    branches:
      - develop
env:
  REGISTRY: brioleur.azurecr.io
  IMAGE_NAME: bricoleur-backend-web
  IMAGE_TAG: latest
  FULL_IMAGE: brioleur.azurecr.io/bricoleur-backend-web:latest

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.FULL_IMAGE }}

      - name: Build image
        run: |
          docker build -t ${{ env.FULL_IMAGE }} .

      - name: Save Docker image to cache
        run: docker save ${{ env.FULL_IMAGE }} | gzip > image.tar.gz

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar.gz

  push:
    name: Push Docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: |
          gunzip -c image.tar.gz | docker load

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:

          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Push Docker image
        run: docker push ${{ env.FULL_IMAGE }}
